Repository AY2425S2-CS2103T-T17-2/tp, pull requests merged in 2025-04, with the labels that each got.

#181 Bug Fix: `lastVisit` command error handling
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/LastVisitCommandParser.java
Labels: type.Bug, severity.High, alpha-bug

#178 Bug Fix: `delLastVisit` reports delete success when lastVisit is empty
  src/main/java/seedu/address/logic/commands/DelLastVisitCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: severity.Low, alpha-bug

#179 Bug fix: `prescribe` alpha bugs
  src/main/java/seedu/address/logic/commands/PrescribeCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PrescribeCommandParser.java
  src/main/java/seedu/address/model/medicine/Medicine.java
  src/test/java/seedu/address/logic/commands/PrescribeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/PrescribeCommandParserTest.java
Labels: type.Bug, severity.Medium, alpha-bug

#182 Bug fix `untag` : Update untag/all feature and error handling
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/UntagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/UntagCommandParser.java
  src/main/java/seedu/address/model/patient/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/DeleteTagCommandTest.java
  src/test/java/seedu/address/logic/commands/UntagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UntagCommandParserTest.java
  src/test/java/seedu/address/model/patient/NameContainsKeywordsPredicateTest.java
Labels: priority.Medium, severity.High, alpha-bug

#180 Bug Fix: `add` command mandates last visit
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
Labels: type.Bug, severity.High, alpha-bug

#189 Userguide v5 branch
  docs/UserGuide.md
Labels: type.Task

#193 Bug Fix: `tag` command unable to warn user when user includes an empty tag
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
Labels: type.Bug, severity.Medium, alpha-bug

#197 Add sequence diagram for LastVisit command
  docs/diagrams/LastVisitSequenceDiagram.puml
Labels: priority.Medium

#199 add command should not be able to add duplicate patients with same name but different case
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/test/java/seedu/address/model/patient/PatientTest.java
Labels: alpha-bug

#209 Modify medicine name validation
  src/main/java/seedu/address/logic/commands/UnprescribeCommand.java
  src/main/java/seedu/address/logic/parser/UnprescribeCommandParser.java
  src/main/java/seedu/address/model/medicine/Medicine.java
Labels: type.Bug, priority.Medium

#215 Medication branch
  src/main/java/seedu/address/model/medicine/Medicine.java
Labels: type.Task

#223 Fix name violations
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DelLastVisitCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/PrescribeCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UnprescribeCommand.java
  src/main/java/seedu/address/logic/commands/UntagCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/DelLastVisitCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/LastVisitCommandParser.java
  src/main/java/seedu/address/logic/parser/UntagCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/patient/Address.java
  src/main/java/seedu/address/model/patient/LastVisit.java
  src/main/java/seedu/address/model/patient/Name.java
  src/main/java/seedu/address/model/patient/UniquePatientList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/data/JsonSerializableAddressBookTest/typicalPatientsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPatientDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/LastVisitCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/patient/PatientTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PatientUtil.java
Labels: type.Bug, priority.High, severity.High

#224 Update userguide branch
  docs/UserGuide.md
Labels: alpha-bug

#229 Update ug with glossary and details
  docs/UserGuide.md
Labels: type.Task

#279 Fix bug where AB-3 is the header
  docs/_sass/minima/_base.scss
Labels: priority.Medium

#280 Update user guide branch
  docs/UserGuide.md
Labels: type.Bug

#281 Bug Fix: Logging file still named as addressbook
  src/main/java/seedu/address/commons/core/LogsCenter.java
Labels: type.Bug

#283 Bug Fix: No number limit enforced to phone number
  src/main/java/seedu/address/model/patient/Phone.java
Labels: type.Bug

#285 Add warning to lastVisit command
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  docs/images/quickstart.png
  src/main/java/seedu/address/logic/commands/LastVisitCommand.java
Labels: type.Bug

#290 Update ug commands
  docs/UserGuide.md
Labels: type.Bug

#293 Fix missing Developer Guide header
  docs/DeveloperGuide.md
Labels: type.Bug

#296 Add duplicate medicine detection for inputs
  src/main/java/seedu/address/logic/commands/PrescribeCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PrescribeCommandParser.java
  src/main/java/seedu/address/logic/parser/UnprescribeCommandParser.java
  src/main/java/seedu/address/model/medicine/Medicine.java
Labels: priority.Medium

#299 Update prescribe and unprescribe code
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/UnprescribeCommandParser.java
  src/main/java/seedu/address/model/medicine/Medicine.java
  src/test/java/seedu/address/logic/parser/UnprescribeCommandParserTest.java
Labels: type.Task

#302 Update UserGuide for v1.6
  docs/UserGuide.md
Labels: priority.High

#305 Update Quick Start in UserGuide
  docs/UserGuide.md
Labels: priority.High

#308 Update typo in UG
  docs/UserGuide.md
Labels: priority.High

#309 Update quick start in UG
  docs/UserGuide.md
Labels: priority.High

#310 Update UG for v1.6
  docs/UserGuide.md
Labels: priority.High
