Repository AY2425S2-CS2103T-T17-2/tp, pull requests merged in 2025-03, with the labels that each got.

#32 Section 3: Glossary
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#29 Section 3: Non-functional requirements
  docs/DeveloperGuide.md
Labels: priority.Low

#35 Add use cases
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#61 Update User Guide To Include `delLastVisit`
  docs/UserGuide.md
Labels: priority.Low

#59 Allow `Patient.lastVisit` to be `null`
  src/main/java/seedu/address/logic/commands/DelLastVisitCommand.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/test/java/seedu/address/logic/commands/DelLastVisitCommandTest.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
Labels: priority.Medium

#65 Branch update userguide
  docs/UserGuide.md
Labels: priority.Low

#66 Update command string
  src/main/java/seedu/address/logic/commands/UnprescribeCommand.java
Labels: priority.Low

#75 Edit outputs for Last Visit command
  src/main/java/seedu/address/logic/commands/LastVisitCommand.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/test/java/seedu/address/logic/commands/LastVisitCommandTest.java
Labels: priority.High

#76 Branch fix patient display
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/UnprescribeCommand.java
Labels: type.Bug

#78 Fix incorrect FXML filepath preventing jar build
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/java/seedu/address/ui/PatientListPanel.java
Labels: type.Bug, priority.High, severity.High

#80 Rename Title from `Address App` to `CareConnect`
  src/main/resources/view/MainWindow.fxml
Labels: priority.Low

#84 Update userguide
  docs/UserGuide.md
Labels: priority.High

#87 Add UnprescribeSequenceDiagram-Logic.puml
  docs/diagrams/UndoSequenceDiagram-Logic.puml
  docs/diagrams/UnprescribeSequenceDiagram-Logic.puml
Labels: priority.High

#93 Update Ui for CareConnect
  src/main/resources/view/CareConnectTheme.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium

#96 Update result for commands
  src/main/java/seedu/address/logic/commands/PrescribeCommand.java
  src/main/java/seedu/address/logic/commands/UnprescribeCommand.java
  src/test/java/seedu/address/logic/commands/PrescribeCommandTest.java
  src/test/java/seedu/address/logic/commands/UnprescribeCommandTest.java
Labels: priority.Medium

#89 Add Tag(s) Without Overwriting
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
Labels: type.Enhancement, type.Task, priority.High, type.*

#91 Fix codestyle in `DelLastVisitCommand.java`
  src/main/java/seedu/address/logic/commands/DelLastVisitCommand.java
  src/main/java/seedu/address/logic/parser/DelLastVisitCommandParser.java
  src/test/java/seedu/address/logic/commands/DelLastVisitCommandTest.java
Labels: type.Bug, priority.Low

#98 Add `TagSequenceDiagram.puml`
  docs/diagrams/TagSequenceDiagram.puml
Labels: type.Task, priority.High, type.*

#106 Fix Ui bug for when patient list is small
  src/main/resources/view/CareConnectTheme.css
Labels: priority.High

#83 Update unprescribe command functionality
  src/main/java/seedu/address/logic/commands/UnprescribeCommand.java
  src/main/java/seedu/address/logic/parser/UnprescribeCommandParser.java
  src/main/java/seedu/address/model/medicine/Medicine.java
  src/test/java/seedu/address/logic/commands/UnprescribeCommandTest.java
  src/test/java/seedu/address/logic/parser/UnprescribeCommandParserTest.java
Labels: priority.High

#111 Fix Typo In `add` Usage Message
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.Bug, priority.High

#114 Update UserGuide for CA3
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  docs/images/jar.png
Labels: priority.High

#133 Renamed client visible instances of addressbook
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/LastVisitCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UnprescribeCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: type.Task

#173 Bug Fix: help Command Ignores Extra Parameters #144 Open
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/HelpCommandParserTest.java
Labels: alpha-bug

#177 Fix invalid index in delete and unprescribe
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/LastVisitCommandParser.java
  src/main/java/seedu/address/logic/parser/UnprescribeCommandParser.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/LastVisitCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnprescribeCommandParserTest.java
Labels: alpha-bug
