Repository AY2425S2-CS2103T-T17-2/tp, pull requests merged in 2025-02, with the labels that each got.

#17 Update Jihan's AboutUs
  docs/AboutUs.md
Labels: priority.Low

#19 Update Sze Ling's about me
  docs/AboutUs.md
Labels: priority.High

#20 Update Luoqi's About Us
  docs/AboutUs.md
Labels: type.Task, priority.Medium, severity.VeryLow

#21 Update Eunice's AboutUs
  docs/AboutUs.md
Labels: priority.High
